### ISSUE TITLE
Stata 13 capability?

### ISSUE THREAD

**Issue by clukewatson** [dballaelliott/binscatter#3]
I have Stata 13 on my laptop. Is there an easy enough way to make your version backwards compatible?

When I tried to run:
"this is version 13.1 of Stata; it cannot run version 15.0 programs
     You can purchase the latest version of Stata by visiting http://www.stata.com."

**Comment by dballaelliott** [comment]
It should be simple enough to let it run on Stata 13 for the model confidence bands - which are the dotted lines. That should only take a second to patch. 

The confidence bands on the binned y-means are transparent, which I don't think was added to Stata until version 15 (though I'm happy to be corrected on that!)... so adding support for the `ci(bins)` option would require a little bit more creativity. The transparency is the only thing that requires version 15, though.

**Comment by dballaelliott** [comment]
Ok, I've just pushed a hotfix  that resolves this as follows: 
- the `ci(model)` functionality is available from version 12.1 forward (should be the same as base binscatter) 
- if `ci(bins)` is passed on a machine running an earlier version than version 15, it will throw an _warning_ message, but the command will execute as if `ci(bins)` wasn't specified. `ci(model bins)` will be treated as if just `ci(model)` was passed. 

(available from `adoupdate` or by copying `net install binscatter, from("https://raw.githubusercontent.com/dballaelliott/binscatter/pkg/") replace` again) 

There is an additional question regarding an alternative way of visualizing uncertainty around the conditional y-means that doesn't involve transparency for users of older versions of Stata. I'll open a new issue as a feature request for this - a great alternative for that hasn't occurred to me yet - I'm all ears if you have thoughts.
